### ISSUE TITLE
BUG-Conflict ### Light Layer Conflict - JEI vs HngDrk ###

### ISSUE THREAD

**Issue by G3R0N1M079** [Shinoow/Hungering-Darkness#7] opened 2019-11-28 11:12 UTC
#### Intro:

This template is intended for bug reports. If you're not posting a bug report, you can remove all of the text that makes up the template. If you are reporting a bug, and you choose not to use this template, your issue will be closed. You may now delete this section and continue on with the report.

#### Description:
With the F7 key, you can activate the light layer on JEI that is RED and Yellow colored.
With your mod HngDrk installed the color change and it's GREY.
Grey is a bit difficult to see on cobblestone etc...
I don't know if this is a BUG a conflict etc...
In case is a HngDrk feature, could you please made the color configurable?

Thank You
Enrico

#### Crash report:
ND

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Hungering Darkness: 

#### Latest log file for when the issue was present:
ND

**Comment by Shinoow** [comment] 2019-11-28 13:26
This mod does pretty much nothing at all on the client side (apart from the config GUI), and judging by https://github.com/feldim2425/MoreOverlays/issues/62, that might be caused by a different combination of mods.
Also, please include the mod version the next time you file a report, that field is there for a reason.

**Comment by G3R0N1M079** [comment] 2019-11-28 14:17
Hello and thank you for your answer
I'm not using more overlay mod, i'm using only JEI and F7 function of JEI to see the light overlay on the floor ( marked as colored X Red or Yellow)
Without your mod the layer is ok
With your mod the layer lose the colors
Sorry for the mod version ommision, my mistake
I tested with the last version of JEI, forge and HD

Enrico

**Comment by Shinoow** [comment] 2019-11-28 18:06
The thing is, JEI doesn't have a light level overlay, and the one in More Overlays ends up acting exactly as you've described, so it would be a bit odd to experience that bug without a mod that adds the feature that you're experiencing issues with.

**Comment by G3R0N1M079** [comment] 2019-11-28 19:46
Ahhhhh... You are right.... I thought that was JEI....
The conflict is with JUST ENOUGH BUTTONS
I install it always along JEI.
I'm very sorry i was completely wrong.

The conflict is with JUST ENOUGH BUTTONS

**Comment by Shinoow** [comment] 2019-11-28 22:37
![2019-11-28_23 30 15](https://user-images.githubusercontent.com/6419600/69833933-49dddf00-1237-11ea-8dba-e3b27c3f525a.png)
Using
- DarknessLib 1.0.0
- Hungering Darkness 1.3.0
- Just Enough Buttons 1.2.3
- JEI 4.15.0.291

Are you sure you aren't using any mods beside those?

**Comment by Shinoow** [comment] 2020-03-01 14:39
Closing this for now. Haven't been able to reproduce the described circumstances with the provided modlist.

**Closed as completed by Shinoow** 2020-03-01 14:39 UTC
Labels: bug
